doctrine_migrations:
<<<<<<< HEAD
     migrations_paths: ['%kernel.project_dir%/src/Migrations']
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    #namespace: DoctrineMigrations
=======
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
>>>>>>> Add initial set of files
