# config/packages/easy_admin.yaml

imports :

      - { resource: easy_admin/basic.yml }
      - { resource: easy_admin/design.yml }
      - { resource: easy_admin/equipes.yml }
      - { resource: easy_admin/jures.yml }
      -  { resource: easy_admin/recompenses.yml }   
      - { resource: easy_admin/users.yml }   
      - { resource: easy_admin/equipesadmin.yml }   
      - { resource: easy_admin/edition.yml }  
      - { resource: easy_admin/classement.yml }
      - { resource: easy_admin/photosequipesinter.yml }  
      - { resource: easy_admin/photosequipescn.yml }  
      - { resource: easy_admin/centrescia.yml } 
      - { resource: easy_admin/elevesinter.yml } 
      - { resource: easy_admin/selectionnees.yml }
      - { resource: easy_admin/fichiersequipesmemoirescn.yml }
      - { resource: easy_admin/fichiersequipesmemoiresinter.yml }
      - { resource: easy_admin/fichiersequipesresumes.yml }
      - { resource: easy_admin/fichiersequipesresumescn.yml }
      - { resource: easy_admin/fichiersequipesfichessecur.yml }
      - { resource: easy_admin/fichiersequipespresentations.yml }
      - { resource: easy_admin/fichiersequipesdiaporamas.yml }
      - { resource: easy_admin/videosequipes.yml }
      - { resource: easy_admin/fichiersequipesautorisations.yml }
      - { resource: easy_admin/visites.yml }
      - { resource: easy_admin/docequipes.yml }
easy_admin:   
    user:
        name_property_path: 'Nom'
    entities:
        User :
            class :  App\Entity\User
            label : 'Utilisateurs'
            list :
                permission: 'ROLE_SUPER_ADMIN'
                fields : ['username', 'nom', 'prenom', 'email', 'roles',{ property: 'is_active',  type: 'boolean' }]
            
                #form:  # <-- 'form' is applied to both 'new' and 'edit' views
            new :
                  fields:
                      - 'username'
                      - 'email'
                      - { property: 'roles', type: 'choice',type_options: { multiple: true, choices:{ 'ROLE_SUPER_ADMIN':'ROLE_SUPER_ADMIN','ROLE_ADMIN':'ROLE_ADMIN','ROLE_PROF': 'ROLE_PROF', 'ROLE_COMITE': 'ROLE_COMITE', 'ROLE_JURY': 'ROLE_JURY', 'ROLE_ORGACIA':'ROLE_ORGACIA', 'ROLE_JURYCIA':'ROLE_JURYCIA'} } }
                      - { property: 'password', type : 'password',}
                      
            password_encoding: { algorithm: 'auto' }
             
            edit :
               fields: 
                       - 'username'
                       - 'email'
                       - { property: 'roles',required: false, type: 'choice', type_options: { multiple: true, choices: { 'ROLE_SUPER_ADMIN':'ROLE_SUPER_ADMIN', 'ROLE_ADMIN':'ROLE_ADMIN', 'ROLE_PROF' : 'ROLE_PROF',  'ROLE_COMITE': 'ROLE_COMITE' , 'ROLE_JURY': 'ROLE_JURY', 'ROLE_ORGACIA':'ROLE_ORGACIA', 'ROLE_JURYCIA':'ROLE_JURYCIA'} } }
                       - { property: 'is_active', type: 'checkbox'}
        
    site_name: <img src="https://upload.wikimedia.org/wikipedia/commons/3/36/Logo_odpf_long.png"" alt="logo des OdpF"  width="160"/>
    design:
        assets:
            favicon: '/assets/backend/favicon.ico'
