fm_elfinder:
    instances:
        default:
            locale: fr # Langue
            editor: ckeditor # Editeur utilisé
            fullscreen: true # Taille d'affichage
            theme: smoothness # Thème à utiliser

            connector:
                debug: false # Désactive le débug
                roots:
                    uploads:
                        show_hidden: false # Masque les fichiers cachés
                        driver: LocalFileSystem # Pilote des fichiers
                        path: images/newsletter # Chemin d'upload
                        upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg' ,'image/JPG',] # Fichiers autorisés
                        upload_deny: [ 'all' ] # Fichiers interdits
                        upload_max_size: 2M # Taille maximum
