<?php

namespace App\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ClassementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassementRepository extends EntityRepository
{
}
