<?php
namespace App\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use App\Entity\Equipesadmin;
use App\Entity\Fichiersequipes;

/**
 * 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichiersequipesRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry, SessionInterface $session)
                    {
                        parent::__construct($registry, Fichiersequipes::class);
                        $this->session = $session;
                    }
    
    
    
public function getEquipesNatSansMemoire(FichiersequipesRepository $er): QueryBuilder
                {  //A reprendre ne donne pas le bon résultat	
                      return $qb1= $er ->createQueryBuilder('f')->select('f')
                                  ->leftJoin('f.equipe','e')
                                  ->where('e.selectionnee  =:selectionnee')
                                  ->setParameter('selectionnee',TRUE)
                                  ->andWhere('f.typefichier =:memoire')
                                 ->setParameter('memoire',NULL)
                                  ->andWhere('f.edition =:edition')
                                 ->setParameter('edition',$er->session->get('edition'))
                                  ->orWhere('f.typefichier>:type')
                                  ->setParameter('type',1)
                                  ->orderBy('e.lettre','ASC');
                 
                }
public function getEquipesInterSansMemoire(FichiersequipesRepository $er): QueryBuilder
                {  //A reprendre ne donne pas le bon résultat	
                       $qb1= $er ->createQueryBuilder('f')->select('f')
                                  ->leftJoin('f.equipe','e')
                                  ->andWhere('f.typefichier =:memoire')
                                 ->setParameter('memoire',NULL)
                                  ->andWhere('f.edition =:edition')
                                 ->setParameter('edition',$er->session->get('edition'))
                                  ->orWhere('f.typefichier>:type')
                                  ->setParameter('type',1)
                                  ->addOrderBy('e.centre','ASC')
                                  ->addOrderBy('e.numero','ASC');
                 return $qb1;
                }
  
                
                
                
}