<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. Copier coller de visites 
 */
class ImageRepository extends EntityRepository
{
    
}

