<?php


namespace App\Repository;

use App\Entity\Notes;
use App\Entity\Coefficients;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends ServiceEntityRepository
{
    public function MonClassement($jure_id)
    {
        $queryBuilder = $this->createQueryBuilder('n');
        $queryBuilder
            ->where('n.jure=:jure_id')
            ->setParameter('jure_id', $jure_id)
            ->orderBy('n.exper*10 + n.demarche*10 + n.oral*12.5 + n.origin*12.5 + n.wgroupe*5', 'DESC');
 // a reprendre avec les coefficients !
        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }

    /**
     * @throws NonUniqueResultException
     */
    public function EquipeDejaNotee($jure_id, $equipe_id)
    {
        $queryBuilder = $this->createQueryBuilder('n');

        $queryBuilder
            ->where('n.jure=:jure_id')
            ->setParameter('jure_id', $jure_id)
            ->andwhere('n.equipe=:equipe_id')
            ->setParameter('equipe_id', $equipe_id);

        $query = $queryBuilder->getQuery();

        return $query->getOneOrNullResult();

    }

}


