<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhrasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhrasesRepository extends EntityRepository
{
}