easy_admin :
     entities :
         Docequipes:
             
             
             class : App\Entity\Docequipes
            # controller: App\Controller\Admin\FichiersequipesController
             templates:
                        list: 'Admin/customizations/docequipes.html.twig' 
             actions :
               - {name : 'new', label : 'Déposer une fichier'}
            
             list :
                  max_results: 10
                  actions: [ { name: 'Lire', icon: 'eye' }, 'delete', 'edit',{name : 'new','label' : 'Nouveau document'}]
                 
                  title : '<h2>Les documents à télécharger</h2>' 
                  fields: 
                    - {property : 'type', label: 'Type'}
                    - {property : 'titre', label: 'Titre'}
                    - {property: 'description', label : 'Description'}
                    - {property : 'fichier', label : 'Fichier', template : 'Admin\customizations\vich_uploader_memoiresinter.html.twig', base_path: '%app.path.docequipes.localhost%/',propertyFile: 'fichierFile'}
                    - {property: 'updatedat', type: 'datetime',label : 'Mis à jour  le '}
                 
             new :
                  title : 'Nouveau document'
                  fields: 
                      - { property : 'type', label : 'Type de document' ,type: 'choice' , type_options :{'choices' : '%status%' }}
                      - { property : 'titre',label : 'Titre du document', type: 'text' }
                      - {property: 'description', label : 'Description'}
                      - { property : 'fichierFile', label: 'Choisir le fichier',  type : 'vich_file',  type_options : {'allow_delete' : false}}
             edit :
                  title : 'Editer le document'
                  fields: 
                      - { property : 'type', label : 'Type de document' ,type: 'choice' , type_options  :{'choices' : '%status%'  }}
                      - { property : 'titre',label : 'Titre du document', type: 'text' }
                      - {property: 'description', label : 'Description'}
                      - { property : 'fichierFile', label: 'Choisir le fichier',  type : 'vich_file',  type_options : {'allow_delete' : false}}       
          
            
                       
    
