easy_admin :
    entities :
        Elevesinter :
            class :  App\Entity\Elevesinter
            label : 'Eleves'
            controller: App\Controller\Admin\ElevesciaController
            templates:
                        list: 'Admin/customizations/list_eleves.html.twig' 
          
            list :
                permission: 'ROLE_COMITE'
                filters :
                    - 'equipe'
                    
                    
                dql_filter : 
               
                batch_actions: ['delete',{name : 'extract_tableau_excel_Elevesns', 'label' : 'Extraire les élèves non sélectionnés'},{name : 'extract_tableau_excel_Eleves_s', 'label' : 'Extraire les élèves  sélectionnés'}]
                fields : 
                    - {property : 'nom'}
                    - {property : 'prenom '}
                    - {property : 'genre'}
                    - {property : 'courriel'}
                    - {property :  'equipe.numero', label : ' Numéro équipe'}
                    - {property : 'equipe.titreProjet', label : 'Projet'}
                    - {property : 'equipe.lyceeLocalite', label : 'ville'}
                    - {property : 'autorisationphotos.fichier', label : 'Autorisations photos'}
                sort : ['equipe.numero', ASC]
                #form:  # <-- 'form' is applied to both 'new' and 'edit' views
            form :
                  fields: 
                       - 'nom'
                       - 'prenom'
                       - 'genre'
                       - 'courriel'
                       - { property: 'equipe', type: 'entity' , type_options : { class : 'App\Entity\Equipesadmin',query_builder : 'App\Repository\EquipesadminRepository::getEquipeInter', 'choice_label' : 'getInfoequipe'}}
            
