easy_admin :
     entities :
         Fichiersequipespresentations:
             
             
             class : App\Entity\Fichiersequipes
             controller: App\Controller\Admin\FichiersequipesController
             actions :
               - {name : 'new', label : 'Déposer une presentation'}
            
             list :
                  max_results: 50
                  actions: [ { name: 'Lire', icon: 'eye' }]
                  batch_actions: [ {name : 'telecharger', icon : 'download'}]
                  filters :
                      - 'edition'
                      
                  dql_filter : 'entity.typefichier = 3 AND national = 1' 
                  title : '<h2>Les présentations orales</h2>' 
                  fields: 
                    - {property : 'equipe.numero', label: 'Numero équipe'}
                    - {property : 'equipe.lettre', label: 'Lettre équipe'}
                    - {property: 'equipe.titreprojet', label : 'Projet'}
                    - {property : 'fichier', label : 'Fichier', template : 'Admin\customizations\vich_uploader_memoiresinter.html.twig', base_path: '%app.path.fichiers.localhost%/presentation',propertyFile: 'fichierFile'}
                    - {property: 'updatedat', type: 'datetime',label : 'Déposé le '}
                  sort: ['equipe.numero','ASC']
                  
             edit :
                  title: ' Les fichiers sont automatiquement renommés' 
                  fields :
                         
                      
                      - { type: 'group', columns: 6, label: '<font color="red" > Choisir l''équipe </font> ' } 
                      - { property : 'equipe', type: 'entity' , type_options : { class : 'App\Entity\Equipesadmin',query_builder : 'App\Repository\EquipesadminRepository::getEquipeInter', 'choice_label' : 'getInfoequipe'}}
                      - { property : 'fichierFile', label: Choisir le résumé',  type : 'vich_file',  type_options : {'allow_delete' : false}}
                          
                 
             new :
                  title : ' Les fichiers sont automatiquement renommés '
                  fields: 
                      - { type: 'group', columns: 6, label: '<font color="red" > Choisir le fichier à déposer </font> ' } 
                      - { property : 'equipe', type: 'entity' , type_options : { class : 'App\Entity\Equipesadmin', query_builder : 'App\Repository\EquipesadminRepository::getEquipeInter', 'choice_label' : 'getInfoequipe'}}
                      - { property : 'fichierFile', label: 'Résumé',  type : 'vich_file',  type_options : {}}
                       
    
