easy_admin :
    entities :
        Prix :
            class : App\Entity\Prix 
            label: Les Prix
            list:
                batch_action: ['delete']
            edit:
                title: 'Modifier un prix'
                fields:
                    - 'prix'
                    - 'classement'
                    - 'attribue' 
                    - { property: 'voix'} 
                    - { property: 'intervenant'} 
                    - { property: 'remisPar'}
                    
            
       
            
        Cadeaux :
              class : App\Entity\Cadeaux       
