easy_admin :
    entities :
        Selectionnees :
            class : App\Entity\Equipes
            label : ' Les équipes du CN '
            controller: App\Controller\Admin\EquipesController 
            list : 
                
                dql_filter:
                actions : ['-delete', '-new']
                max_results: 25
                sort: ['lettre', 'ASC']
                batch_actions: [ {name : 'extractionTableauPourMailingJures', 'label' : 'Tableaujuréspourmailinsallesvisio'}]  
                fields :
               
                  - 'lettre'
                  #- { property : 'titreProjet', label : 'Projet'}
                  - { property : 'infoequipe.lyceeAcademie' , label : 'Académie'}
                  - { property : 'infoequipe.Lycee', label : 'Lycée'}
                  - { property : 'infoequipe.TitreProjet', label : 'Projet'}
                  - { property : 'heure', label : 'Heure de passage jury'}
                  - { property : 'salle', label : 'Salle'}
                  - { property : 'code', label : 'code'}
                  - { property : 'sallesecours', label : 'Sallesecours'}
                  - { property : 'hote.PrenomNom', label : 'hote'}
                  - { property : 'interlocuteur.PrenomNom', label : 'interlocuteur'}
            edit :
                  fields :
                  
                  - 'lettre'
                  #- { property : 'titreProjet', label : 'Projet'}
                  - { property : 'infoequipe.lyceeAcademie' , label : 'Académie',disabled : true}
                  - { property : 'infoequipe.Lycee', label : 'Lycée', disabled : true}
                  - { property : 'infoequipe.TitreProjet', label : 'Projet', disabled : true}
                  - { property : 'heure', label : 'Heure de passage jury'}
                  - { property : 'salle', label : 'Salle'}
                  - { property : 'sallesecours', label : 'Sallesecours'}
                  - { property : 'code', label : 'code'}
                  - { property : 'hote', label : 'hote', type : 'entity',  type_options : { class : 'App\Entity\User', query_builder : 'App\Repository\UserRepository::getHote', 'choice_label' : 'getNomPrenom'}}
                  - { property : 'interlocuteur', label : 'interlocuteur', type : 'entity',  type_options : { class : 'App\Entity\User', query_builder : 'App\Repository\UserRepository::getInterlocuteur', 'choice_label' : 'getNomPrenom'}}